[[headers]]
  for = "/*"
  [headers.values]
    Permissions-Policy = "interest-cohort=()"
    Content-Security-Policy = "upgrade-insecure-requests"
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[build]
  publish = "build"
  command = "yarn build"

[build.processing]
  skip_processing = true

[[redirects]]
  from = "https://ichik.xyz/*"
  to = "https://vaitenko.com/:splat"
  status = 301
  force = true